import { getSentimentDashboardData } from "@/lib/actions/sentiment.actions";
import { getAiMarketSummary } from "@/lib/actions/ai.actions";
import { getNews } from "@/lib/actions/finnhub.actions";
import { TrendingUp, TrendingDown, Zap, BarChart3, Sparkles } from "lucide-react";
import Link from "next/link";

export default async function SentimentPage() {
  const articles = await getNews();
  const [data, aiSummary] = await Promise.all([
    getSentimentDashboardData(articles),
    getAiMarketSummary(articles),
  ]);

  if (!data)
    return <div className="p-10 text-white">Analyzing market signals...</div>;

  return (
    <div className="max-w-7xl mx-auto p-6 space-y-10">
      <header>
        <h1 className="text-4xl font-black text-white italic tracking-tighter">
          SENTIMENT HUB
        </h1>
        <p className="text-gray-500">
          Signal analysis of {data.totalAnalyzed} real-time market headlines
        </p>
      </header>

      {/* AI Market Summary — real Gemini call, clearly labeled */}
      <div className="bg-gray-800 border border-indigo-500/20 rounded-3xl p-8 relative overflow-hidden">
        <h2 className="text-gray-400 font-bold mb-4 flex items-center gap-2 uppercase text-xs">
          <Sparkles size={14} className="text-indigo-500" /> AI Market Summary
        </h2>
        {aiSummary ? (
          <>
            <p className="text-white text-lg font-medium leading-relaxed">
              {aiSummary.summary}
            </p>
            <div className="mt-4 flex items-center gap-2">
              <span className="text-xs text-gray-500 uppercase tracking-wide">
                Confidence score
              </span>
              <span className="text-indigo-400 font-bold">{aiSummary.score}/100</span>
            </div>
          </>
        ) : (
          <p className="text-gray-500 text-sm italic">
            AI summary unavailable right now — showing signal data below instead.
          </p>
        )}
        <p className="text-gray-600 text-[10px] mt-4 uppercase tracking-wide">
          Generated by Gemini from today&apos;s top headlines · not financial advice
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* 1. Market Mood Gauge */}
        <div className="bg-gray-800 border border-gray-600/50 rounded-3xl p-8 flex flex-col items-center justify-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-linear-to-r from-rose-500 via-yellow-500 to-emerald-500" />
          <h2 className="text-gray-400 font-bold mb-6 flex items-center gap-2 uppercase text-xs">
            <Zap size={14} className="text-yellow-500" /> Market Mood
          </h2>
          <div className="text-6xl font-black text-white mb-2">
            {Math.round(data.marketSentiment)}%
          </div>
          <div className="text-emerald-400 font-bold text-sm uppercase tracking-widest">
            Bullish Bias
          </div>
          <p className="text-gray-500 text-[10px] mt-4 text-center">
            Calculated from news volume & headline polarity
          </p>
        </div>

        {/* 2. Most Mentioned Stocks (Power List) */}
        <div className="lg:col-span-2 bg-gray-800 border border-gray-600/50 rounded-3xl p-8">
          <h2 className="text-gray-400 font-bold mb-6 flex items-center gap-2 uppercase text-xs">
            <BarChart3 size={14} className="text-indigo-500" /> Trending Assets
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {data.leaderboard.map((item) => (
              <div
                key={item.symbol}
                className="bg-gray-900 p-4 rounded-2xl border border-gray-600/50 flex items-center justify-between group hover:border-indigo-500/50 transition-all"
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 bg-indigo-600/10 rounded-xl flex items-center justify-center font-black text-indigo-400">
                    {item.symbol[0]}
                  </div>
                  <div>
                    <div className="text-white font-bold">${item.symbol}</div>
                    <div className="text-[10px] text-gray-500">
                      {item.mentionCount} recent mentions
                    </div>
                  </div>
                </div>
                <div className="text-right">
                  <div
                    className={
                      item.score >= 0 ? "text-emerald-400" : "text-rose-400"
                    }
                  >
                    {item.score >= 0 ? (
                      <TrendingUp size={16} />
                    ) : (
                      <TrendingDown size={16} />
                    )}
                  </div>
                  {item.topTarget && (
                    <div className="text-[9px] font-black text-indigo-500 mt-1">
                      {item.topTarget} TGT
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 3. Alerts CTA */}
      <div className="bg-linear-to-br from-indigo-600/20 to-transparent border border-indigo-500/20 rounded-3xl p-10 text-center">
        <h3 className="text-white font-bold text-xl mb-2">
          Act on what you're seeing
        </h3>
        <p className="text-gray-400 max-w-md mx-auto text-sm mb-6">
          Set a price alert on any watchlist symbol and we&apos;ll email you
          the moment it hits your target.
        </p>
        <Link
          href="/watchlist"
          className="inline-block bg-indigo-600 hover:bg-indigo-500 text-white font-bold px-8 py-3 rounded-full text-sm transition-all shadow-xl shadow-indigo-600/20"
        >
          Set Price Alerts
        </Link>
      </div>
    </div>
  );
}
